#!/usr/bin/env python3
"""Convert metallic-rs f64 gamma table literals to C (kernel/gammatab.h).

Mechanical: parse the Rust const array bodies, pull float literals in order,
repack into C struct-initializer arrays.  Not run at build time; regenerate by
hand if the rs tables change.
"""
import re, sys

RS = "/home/jdh8/src/metallic-rs/src/f64_"
gamma = open(f"{RS}/gamma.rs").read()
trig = open(f"{RS}/trig.rs").read()

FLOAT = re.compile(r"-?(?:\d+\.\d*(?:[eE][-+]?\d+)?|\d+[eE][-+]?\d+|\.\d+(?:[eE][-+]?\d+)?)")

def body(src, name):
    """Text between `const NAME ... = [` and the matching `\n];`."""
    i = src.index(f"const {name}")
    i = src.index("= [", i) + 3
    j = src.index("\n];", i)
    return src[i:j]

def floats(src, name):
    return [float(x) for x in FLOAT.findall(body(src, name))]

def chunk(xs, n):
    assert len(xs) % n == 0, (name, len(xs), n)
    return [xs[k:k+n] for k in range(0, len(xs), n)]

def lit(v):
    return repr(v)

out = []
w = out.append
w("#ifndef METALLIC_KERNEL_GAMMATAB_H")
w("#define METALLIC_KERNEL_GAMMATAB_H")
w("")
w("/* Generated by tools_gen_gammatab.py from metallic-rs f64 gamma tables.")
w(" * Do not edit by hand; re-run the generator instead. */")
w("")

# --- TGAMMA_TD: 39 TripleDouble (high, mid, low) ---
td = chunk(floats(gamma, "TGAMMA_TD"), 3)
assert len(td) == 39, len(td)
w(f"static const td_t TGAMMA_TD[{len(td)}] = {{")
for a, b, c in td:
    w(f"    {{ {lit(a)}, {lit(b)}, {lit(c)} }},")
w("};")
w("")

# --- TGAMMA_TABLE: 273 GammaCell (c0..c3 dd, tail[8] f64) = 16 doubles ---
cells = chunk(floats(gamma, "TGAMMA_TABLE"), 16)
assert len(cells) == 273, len(cells)
w(f"static const gamma_cell_t TGAMMA_TABLE[{len(cells)}] = {{")
for v in cells:
    c0, c1, c2, c3, tail = v[0:2], v[2:4], v[4:6], v[6:8], v[8:16]
    w("    { " +
      f"{{{lit(c0[0])},{lit(c0[1])}}}, {{{lit(c1[0])},{lit(c1[1])}}}, " +
      f"{{{lit(c2[0])},{lit(c2[1])}}}, {{{lit(c3[0])},{lit(c3[1])}}}, " +
      "{ " + ", ".join(lit(t) for t in tail) + " } },")
w("};")
w("")

# --- SINPI_TABLE: 65 DoubleDouble ---
sp = chunk(floats(trig, "SINPI_TABLE"), 2)
assert len(sp) == 65, len(sp)
w(f"static const dd_t GAMMA_SINPI_TABLE[{len(sp)}] = {{")
for a, b in sp:
    w(f"    {{ {lit(a)}, {lit(b)} }},")
w("};")
w("")

w("#endif")
open("/home/jdh8/src/metallic/src/math/double/kernel/gammatab.h", "w").write("\n".join(out) + "\n")
print("wrote gammatab.h:", len(td), "td,", len(cells), "cells,", len(sp), "sinpi")
