#!/usr/bin/env python3
"""Convert metallic-rs f64 gamma table literals to C (kernel/gammatab.h).

Mechanical: parse the Rust const array bodies, pull literals in order, repack
into C struct-initializer arrays.  Not run at build time; regenerate by hand if
the rs tables change.  Sources: f64_/{gamma.rs, gamma_td_tables.rs,
gamma_piece_tables.rs, trig.rs}.
"""
import re

RS = "/home/jdh8/src/metallic-rs/src/f64_"
gamma = open(f"{RS}/gamma.rs").read()
tdt = open(f"{RS}/gamma_td_tables.rs").read()
piece = open(f"{RS}/gamma_piece_tables.rs").read()
trig = open(f"{RS}/trig.rs").read()

FLOAT = re.compile(r"-?(?:\d+\.\d*(?:[eE][-+]?\d+)?|\d+[eE][-+]?\d+|\.\d+(?:[eE][-+]?\d+)?)")
HEX = re.compile(r"0x[0-9a-fA-F]+")
PAIR = re.compile(r"\(\s*(\d+)\s*,\s*(-?\d+)\s*\)")

def body(src, name):
    i = src.index(f"const {name}")
    i = src.index("= [", i) + 3
    j = src.index("\n];", i)
    return src[i:j]

def floats(src, name):
    return [float(x) for x in FLOAT.findall(body(src, name))]

def chunk(xs, n):
    assert len(xs) % n == 0, (len(xs), n)
    return [xs[k:k+n] for k in range(0, len(xs), n)]

def L(v):
    return repr(v)

out = ["#ifndef METALLIC_KERNEL_GAMMATAB_H", "#define METALLIC_KERNEL_GAMMATAB_H", "",
       "/* Generated by tools_gen_gammatab.py from metallic-rs f64 gamma tables.",
       " * Do not edit by hand; re-run the generator instead. */", ""]
w = out.append

def td_array(src, name, cname, expect):
    v = chunk(floats(src, name), 3)
    assert len(v) == expect, (name, len(v))
    w(f"static const td_t {cname}[{len(v)}] = {{")
    for a, b, c in v:
        w(f"    {{ {L(a)}, {L(b)}, {L(c)} }},")
    w("};\n")

def dd_array(src, name, cname, expect):
    v = chunk(floats(src, name), 2)
    assert len(v) == expect, (name, len(v))
    w(f"static const dd_t {cname}[{len(v)}] = {{")
    for a, b in v:
        w(f"    {{ {L(a)}, {L(b)} }},")
    w("};\n")

def f64_array(src, name, cname, expect):
    v = floats(src, name)
    assert len(v) == expect, (name, len(v))
    w(f"static const double {cname}[{len(v)}] = {{ " + ", ".join(L(x) for x in v) + " };\n")

def f64_2d(src, name, cname, rows, cols):
    v = chunk(floats(src, name), cols)
    assert len(v) == rows, (name, len(v))
    w(f"static const double {cname}[{rows}][{cols}] = {{")
    for row in v:
        w("    { " + ", ".join(L(x) for x in row) + " },")
    w("};\n")

def dd_2d(src, name, cname, rows, cols):
    v = chunk(floats(src, name), cols * 2)
    assert len(v) == rows, (name, len(v))
    w(f"static const dd_t {cname}[{rows}][{cols}] = {{")
    for row in v:
        cells = ", ".join(f"{{{L(row[2*i])},{L(row[2*i+1])}}}" for i in range(cols))
        w("    { " + cells + " },")
    w("};\n")

# ── tgamma tables ──
td_array(gamma, "TGAMMA_TD", "TGAMMA_TD", 39)

cells = chunk(floats(gamma, "TGAMMA_TABLE"), 16)
assert len(cells) == 273
w(f"static const gamma_cell_t TGAMMA_TABLE[{len(cells)}] = {{")
for v in cells:
    c = v[0:8]; tail = v[8:16]
    w("    { " + ", ".join(f"{{{L(c[2*i])},{L(c[2*i+1])}}}" for i in range(4)) +
      ", { " + ", ".join(L(t) for t in tail) + " } },")
w("};\n")

dd_array(trig, "SINPI_TABLE", "GAMMA_SINPI_TABLE", 65)

# ── lgamma tables ──
td_array(gamma, "LGAMMA_TAIL_TD", "LGAMMA_TAIL_TD", 10)
f64_array(gamma, "LGAMMA_TAIL_F64", "LGAMMA_TAIL_F64", 10)
f64_array(gamma, "LGAMMA_TAIL_F64_FAR", "LGAMMA_TAIL_F64_FAR", 6)
td_array(gamma, "SINPI_OVER_ARG_TD", "SINPI_OVER_ARG_TD", 21)
td_array(gamma, "COSPI_TD", "COSPI_TD", 21)

# accurate ln (CORE-MATH as_logd) tables
pairs = PAIR.findall(body(tdt, "LOGD_B"))
assert len(pairs) == 32, len(pairs)
w(f"static const logd_b_t LOGD_B[32] = {{")
for c0, c1 in pairs:
    w(f"    {{ {c0}, {c1} }},")
w("};\n")
f64_array(tdt, "LOGD_R1", "LOGD_R1", 33)
f64_array(tdt, "LOGD_R2", "LOGD_R2", 33)
f64_2d(tdt, "LOGD_H1", "LOGD_H1", 33, 3)
f64_2d(tdt, "LOGD_H2", "LOGD_H2", 33, 3)
dd_array(tdt, "LOGD_C", "LOGD_C", 9)
td_array(tdt, "LGAMMA_ROOT1_TD", "LGAMMA_ROOT1_TD", 42)
td_array(tdt, "LGAMMA_ROOT2_TD", "LGAMMA_ROOT2_TD", 34)

# CORE-MATH piecewise lgamma over [0.5, 8)
borders = HEX.findall(body(piece, "LGAMMA_PIECE_BORDERS"))
assert len(borders) == 20, len(borders)
w(f"static const uint32_t LGAMMA_PIECE_BORDERS[20] = {{ " + ", ".join(b + "u" for b in borders) + " };\n")
f64_array(piece, "LGAMMA_PIECE_OFFS", "LGAMMA_PIECE_OFFS", 19)
f64_2d(piece, "LGAMMA_PIECE_CL", "LGAMMA_PIECE_CL", 19, 8)
dd_2d(piece, "LGAMMA_PIECE_CH", "LGAMMA_PIECE_CH", 19, 5)

# accurate sin/cos kernels (for abs_sinpi_dd)
dd_array(trig, "SIN_KERNEL", "GAMMA_SIN_KERNEL", 13)
dd_array(trig, "COS_KERNEL", "GAMMA_COS_KERNEL", 13)

w("#endif")
open("/home/jdh8/src/metallic/src/math/double/kernel/gammatab.h", "w").write("\n".join(out) + "\n")
print("wrote gammatab.h:", len(out), "lines")
