/* Correctly-rounded double atanh.
 *
 * atanh(x) = (1/2) * ln((1+x)/(1-x)) = (1/2) * ln1p(u)
 *   where u = 2x/(1-x).
 *
 * Fast path:
 *   u = 2x/(1-x) as a double-double (u_hi, u_lo).
 *   Form arg = 1 + u as a double-double via two-sum, then:
 *   - For |u| <= 1/256: logtab_ln1p_kernel_((u_hi, u_lo)).
 *   - Otherwise: logtab_ln_dd_(arg_hi) + arg_lo/arg_hi (first-order Taylor).
 *   Halve the result.
 *
 * Accurate path (Ziv fallback):
 *   For |x| <= 0.5: dint Taylor series with exact 128-bit coefficients:
 *     atanh(x) = x*(1/1 + x^2/3 + x^4/5 + ... + x^{128}/129)
 *   For |x| > 0.5: dint_ln_((1+|x|)/(1-|x|)) / 2 via Newton reciprocal.
 *
 * Special cases: atanh(±1)=±∞, |x|>1=NaN, atanh(0)=0, atanh(NaN)=NaN.
 */

#include "kernel/logtab.h"
#include "kernel/dint.h"
#include <math.h>

/* Fast-path error bound (relative to r.hi, as in asin.c).
 * The logtab double-double path has up to ~0.5 ULP error; using 2 ULP of r.hi
 * ensures the Ziv test triggers a fallback whenever fast-path and true result
 * straddle a double rounding boundary. */
#define ATANH_ERR(r_hi) ((r_hi) * 0x1p-51)

/* Exact 128-bit representations of 1/(2k+1) for k = 0..64.
 * Generated by: round(2^127 / (2k+1)), normalized so bit 127 is set. */
static const dint_t atanh_inv_odd_[] = {
    { 0,   0, ((unsigned __int128)0x8000000000000000ULL << 64) | 0x0000000000000000ULL },  /* 1/1 */
    { 0,  -2, ((unsigned __int128)0xaaaaaaaaaaaaaaaaULL << 64) | 0xaaaaaaaaaaaaaaabULL },  /* 1/3 */
    { 0,  -3, ((unsigned __int128)0xccccccccccccccccULL << 64) | 0xcccccccccccccccdULL },  /* 1/5 */
    { 0,  -3, ((unsigned __int128)0x9249249249249249ULL << 64) | 0x2492492492492492ULL },  /* 1/7 */
    { 0,  -4, ((unsigned __int128)0xe38e38e38e38e38eULL << 64) | 0x38e38e38e38e38e4ULL },  /* 1/9 */
    { 0,  -4, ((unsigned __int128)0xba2e8ba2e8ba2e8bULL << 64) | 0xa2e8ba2e8ba2e8baULL },  /* 1/11 */
    { 0,  -4, ((unsigned __int128)0x9d89d89d89d89d89ULL << 64) | 0xd89d89d89d89d89eULL },  /* 1/13 */
    { 0,  -4, ((unsigned __int128)0x8888888888888888ULL << 64) | 0x8888888888888889ULL },  /* 1/15 */
    { 0,  -5, ((unsigned __int128)0xf0f0f0f0f0f0f0f0ULL << 64) | 0xf0f0f0f0f0f0f0f1ULL },  /* 1/17 */
    { 0,  -5, ((unsigned __int128)0xd79435e50d79435eULL << 64) | 0x50d79435e50d7943ULL },  /* 1/19 */
    { 0,  -5, ((unsigned __int128)0xc30c30c30c30c30cULL << 64) | 0x30c30c30c30c30c3ULL },  /* 1/21 */
    { 0,  -5, ((unsigned __int128)0xb21642c8590b2164ULL << 64) | 0x2c8590b21642c859ULL },  /* 1/23 */
    { 0,  -5, ((unsigned __int128)0xa3d70a3d70a3d70aULL << 64) | 0x3d70a3d70a3d70a4ULL },  /* 1/25 */
    { 0,  -5, ((unsigned __int128)0x97b425ed097b425eULL << 64) | 0xd097b425ed097b42ULL },  /* 1/27 */
    { 0,  -5, ((unsigned __int128)0x8d3dcb08d3dcb08dULL << 64) | 0x3dcb08d3dcb08d3eULL },  /* 1/29 */
    { 0,  -5, ((unsigned __int128)0x8421084210842108ULL << 64) | 0x4210842108421084ULL },  /* 1/31 */
    { 0,  -6, ((unsigned __int128)0xf83e0f83e0f83e0fULL << 64) | 0x83e0f83e0f83e0f8ULL },  /* 1/33 */
    { 0,  -6, ((unsigned __int128)0xea0ea0ea0ea0ea0eULL << 64) | 0xa0ea0ea0ea0ea0eaULL },  /* 1/35 */
    { 0,  -6, ((unsigned __int128)0xdd67c8a60dd67c8aULL << 64) | 0x60dd67c8a60dd67dULL },  /* 1/37 */
    { 0,  -6, ((unsigned __int128)0xd20d20d20d20d20dULL << 64) | 0x20d20d20d20d20d2ULL },  /* 1/39 */
    { 0,  -6, ((unsigned __int128)0xc7ce0c7ce0c7ce0cULL << 64) | 0x7ce0c7ce0c7ce0c8ULL },  /* 1/41 */
    { 0,  -6, ((unsigned __int128)0xbe82fa0be82fa0beULL << 64) | 0x82fa0be82fa0be83ULL },  /* 1/43 */
    { 0,  -6, ((unsigned __int128)0xb60b60b60b60b60bULL << 64) | 0x60b60b60b60b60b6ULL },  /* 1/45 */
    { 0,  -6, ((unsigned __int128)0xae4c415c9882b931ULL << 64) | 0x0572620ae4c415caULL },  /* 1/47 */
    { 0,  -6, ((unsigned __int128)0xa72f05397829cbc1ULL << 64) | 0x4e5e0a72f0539783ULL },  /* 1/49 */
    { 0,  -6, ((unsigned __int128)0xa0a0a0a0a0a0a0a0ULL << 64) | 0xa0a0a0a0a0a0a0a1ULL },  /* 1/51 */
    { 0,  -6, ((unsigned __int128)0x9a90e7d95bc609a9ULL << 64) | 0x0e7d95bc609a90e8ULL },  /* 1/53 */
    { 0,  -6, ((unsigned __int128)0x94f2094f2094f209ULL << 64) | 0x4f2094f2094f2095ULL },  /* 1/55 */
    { 0,  -6, ((unsigned __int128)0x8fb823ee08fb823eULL << 64) | 0xe08fb823ee08fb82ULL },  /* 1/57 */
    { 0,  -6, ((unsigned __int128)0x8ad8f2fba9386822ULL << 64) | 0xb63cbeea4e1a08aeULL },  /* 1/59 */
    { 0,  -6, ((unsigned __int128)0x864b8a7de6d1d608ULL << 64) | 0x64b8a7de6d1d6086ULL },  /* 1/61 */
    { 0,  -6, ((unsigned __int128)0x8208208208208208ULL << 64) | 0x2082082082082082ULL },  /* 1/63 */
    { 0,  -7, ((unsigned __int128)0xfc0fc0fc0fc0fc0fULL << 64) | 0xc0fc0fc0fc0fc0fcULL },  /* 1/65 */
    { 0,  -7, ((unsigned __int128)0xf4898d5f85bb3950ULL << 64) | 0x3d226357e16ece54ULL },  /* 1/67 */
    { 0,  -7, ((unsigned __int128)0xed7303b5cc0ed730ULL << 64) | 0x3b5cc0ed7303b5ccULL },  /* 1/69 */
    { 0,  -7, ((unsigned __int128)0xe6c2b4481cd85689ULL << 64) | 0x039b0ad12073615aULL },  /* 1/71 */
    { 0,  -7, ((unsigned __int128)0xe070381c0e070381ULL << 64) | 0xc0e070381c0e0704ULL },  /* 1/73 */
    { 0,  -7, ((unsigned __int128)0xda740da740da740dULL << 64) | 0xa740da740da740daULL },  /* 1/75 */
    { 0,  -7, ((unsigned __int128)0xd4c77b03531dec0dULL << 64) | 0x4c77b03531dec0d5ULL },  /* 1/77 */
    { 0,  -7, ((unsigned __int128)0xcf6474a8819ec8e9ULL << 64) | 0x51033d91d2a2067bULL },  /* 1/79 */
    { 0,  -7, ((unsigned __int128)0xca4587e6b74f0329ULL << 64) | 0x161f9add3c0ca458ULL },  /* 1/81 */
    { 0,  -7, ((unsigned __int128)0xc565c87b5f9d4d1bULL << 64) | 0xc2503159721ed7e7ULL },  /* 1/83 */
    { 0,  -7, ((unsigned __int128)0xc0c0c0c0c0c0c0c0ULL << 64) | 0xc0c0c0c0c0c0c0c1ULL },  /* 1/85 */
    { 0,  -7, ((unsigned __int128)0xbc52640bc52640bcULL << 64) | 0x52640bc52640bc52ULL },  /* 1/87 */
    { 0,  -7, ((unsigned __int128)0xb81702e05c0b8170ULL << 64) | 0x2e05c0b81702e05cULL },  /* 1/89 */
    { 0,  -7, ((unsigned __int128)0xb40b40b40b40b40bULL << 64) | 0x40b40b40b40b40b4ULL },  /* 1/91 */
    { 0,  -7, ((unsigned __int128)0xb02c0b02c0b02c0bULL << 64) | 0x02c0b02c0b02c0b0ULL },  /* 1/93 */
    { 0,  -7, ((unsigned __int128)0xac7691840ac76918ULL << 64) | 0x40ac7691840ac769ULL },  /* 1/95 */
    { 0,  -7, ((unsigned __int128)0xa8e83f5717c0a8e8ULL << 64) | 0x3f5717c0a8e83f57ULL },  /* 1/97 */
    { 0,  -7, ((unsigned __int128)0xa57eb50295fad40aULL << 64) | 0x57eb50295fad40a5ULL },  /* 1/99 */
    { 0,  -7, ((unsigned __int128)0xa237c32b16cfd772ULL << 64) | 0x0f353a4c0a237c33ULL },  /* 1/101 */
    { 0,  -7, ((unsigned __int128)0x9f1165e7254813e2ULL << 64) | 0x2cbce4a9027c4598ULL },  /* 1/103 */
    { 0,  -7, ((unsigned __int128)0x9c09c09c09c09c09ULL << 64) | 0xc09c09c09c09c09cULL },  /* 1/105 */
    { 0,  -7, ((unsigned __int128)0x991f1a515885fb37ULL << 64) | 0x072d753bd02647c7ULL },  /* 1/107 */
    { 0,  -7, ((unsigned __int128)0x964fda6c0964fda6ULL << 64) | 0xc0964fda6c0964feULL },  /* 1/109 */
    { 0,  -7, ((unsigned __int128)0x939a85c40939a85cULL << 64) | 0x40939a85c40939a8ULL },  /* 1/111 */
    { 0,  -7, ((unsigned __int128)0x90fdbc090fdbc090ULL << 64) | 0xfdbc090fdbc090feULL },  /* 1/113 */
    { 0,  -7, ((unsigned __int128)0x8e78356d1408e783ULL << 64) | 0x56d1408e78356d14ULL },  /* 1/115 */
    { 0,  -7, ((unsigned __int128)0x8c08c08c08c08c08ULL << 64) | 0xc08c08c08c08c08cULL },  /* 1/117 */
    { 0,  -7, ((unsigned __int128)0x89ae4089ae4089aeULL << 64) | 0x4089ae4089ae408aULL },  /* 1/119 */
    { 0,  -7, ((unsigned __int128)0x8767ab5f34e47ef1ULL << 64) | 0x30a9419637021d9fULL },  /* 1/121 */
    { 0,  -7, ((unsigned __int128)0x8534085340853408ULL << 64) | 0x5340853408534085ULL },  /* 1/123 */
    { 0,  -7, ((unsigned __int128)0x83126e978d4fdf3bULL << 64) | 0x645a1cac083126e9ULL },  /* 1/125 */
    { 0,  -7, ((unsigned __int128)0x8102040810204081ULL << 64) | 0x0204081020408102ULL },  /* 1/127 */
    { 0,  -8, ((unsigned __int128)0xfe03f80fe03f80feULL << 64) | 0x03f80fe03f80fe04ULL },  /* 1/129 */
};

/* Accurate atanh for |x| <= 0.5: Taylor series with exact 128-bit coefficients.
 * atanh(x) = x * sum_{k=0}^{64} x^{2k} / (2k+1)
 * Horner: sum_k = 1/(2k+1) + x^2 * sum_{k+1}, evaluated from k=64 down to k=0. */
static inline dint_t atanh_taylor_dint_(double ax)
{
    dint_t xd = dint_from_f64_(ax);
    dint_t x2 = dint_mul_(&xd, &xd);

    dint_t sum = atanh_inv_odd_[64];  /* 1/129 */
    for (int k = 63; k >= 0; --k) {
        sum = dint_mul_(&x2, &sum);
        sum = dint_add_(&atanh_inv_odd_[k], &sum);
    }
    return dint_mul_(&xd, &sum);
}

static double atanh_accurate_(double x)
{
    double ax = fabs(x);
    dint_t result;

    if (ax <= 0.5) {
        result = atanh_taylor_dint_(ax);
    } else {
        dint_t axd = dint_from_f64_(ax);
        dint_t one = { 0, 0, (unsigned __int128)0x8000000000000000ULL << 64 };
        dint_t two = { 0, 1, (unsigned __int128)0x8000000000000000ULL << 64 };

        dint_t neg_ax = { 1, axd.ex, axd.m };
        dint_t b = dint_add_(&one, &neg_ax);  /* 1 - ax */

        double bd = dint_to_f64_(&b);
        dint_t r = dint_from_f64_(1.0 / bd);
        for (int k = 0; k < 2; ++k) {
            dint_t br = dint_mul_(&b, &r);
            dint_t neg_br = { !br.sgn, br.ex, br.m };
            dint_t t = dint_add_(&two, &neg_br);
            r = dint_mul_(&r, &t);
        }

        dint_t a = dint_add_(&one, &axd);
        dint_t ratio = dint_mul_(&a, &r);
        dint_t ln_r = dint_ln_(ratio);
        ln_r.ex -= 1;
        result = ln_r;
    }

    return copysign(dint_to_f64_(&result), x);
}

double atanh(double x)
{
    if (x != x)
        return x;

    double ax = fabs(x);

    if (ax > 1.0)
        return (x - x) / (x - x);  /* NaN, domain error */
    if (ax == 1.0)
        return copysign(INFINITY, x);

    /* |x| < 2^-27: atanh(x) = x, error < x^3/3 < 0.5 ulp(x). */
    if (ax < 0x1p-27)
        return x;

    /* u = 2*ax/(1-ax) as a double-double (u_hi, u_lo). */
    double den = 1.0 - ax;
    double two_ax = 2.0 * ax;  /* exact */
    double u_hi = two_ax / den;
    double u_lo = (two_ax - u_hi * den) / den;

    exptab_sum_ r;

    if (u_hi <= 0x1p-8) {
        /* Small u: logtab_ln1p_kernel_ is accurate for |r| <= 1/256. */
        exptab_sum_ u = { u_hi, u_lo };
        r = logtab_ln1p_kernel_(u);
    } else {
        /* Compute arg = 1 + u as a double-double.
         * For u_hi large (>> 1), 1 is negligible: arg_hi = u_hi, arg_lo = u_lo + 1 - arg_hi.
         * Use two-sum to be correct in all cases. */
        double arg_hi = 1.0 + u_hi;
        double arg_lo_s = arg_hi - 1.0;   /* rounding error from 1 + u_hi */
        double arg_lo = (u_hi - arg_lo_s) + u_lo;
        /* Now arg_hi + arg_lo ≈ 1 + u = (1+ax)/(1-ax) to ~106 bits. */

        /* ln(arg_hi + arg_lo) ≈ logtab_ln_dd_(arg_hi) + arg_lo/arg_hi */
        r = logtab_ln_dd_(arg_hi);
        r.lo += arg_lo / arg_hi;
    }

    /* Halve: atanh(x) = (1/2) * ln1p(u) */
    r.hi *= 0.5;
    r.lo *= 0.5;

    double err   = ATANH_ERR(r.hi);
    double left  = r.hi + (r.lo - err);
    double right = r.hi + (r.lo + err);

    if (left != right)
        return atanh_accurate_(x);

    return copysign(left, x);
}
