#include "kernel/sinhtab.h"
#include <math.h>
#include <stdint.h>

/* Upper limit of the result-anchored small-|x| series leg. */
#define SINH_SMALL 0.25

/* sinh(x) = x + x^3·S(x^2) for |x| < SINH_SMALL, where ½(e^x − e^-x) cancels.
 * Fast leg: plain-f64 S (degree 8, truncation ~2^-90 over the band) with an
 * x^3-scaled Ziv gate; straddle defers to the double-double series.  Port of
 * metallic-rs sinh_small. */
static double sinh_small_(double x)
{
    static const double s_fast[8] = {
        0.16666666666666666,   0.008333333333333333,  0.0001984126984126984,
        2.7557319223985893e-6, 2.505210838544172e-8,  1.6059043836821613e-10,
        7.647163731819816e-13, 2.8114572543455206e-15,
    };
    static const double s_dd[12][2] = {
        { 0.16666666666666666,    9.25185853854297e-18   },
        { 0.008333333333333333,   1.1564823173178714e-19 },
        { 0.0001984126984126984,  1.7209558293420705e-22 },
        { 2.7557319223985893e-6, -1.858393274046472e-22  },
        { 2.505210838544172e-8,  -1.448814070935912e-24  },
        { 1.6059043836821613e-10, 1.2585294588752098e-26 },
        { 7.647163731819816e-13,  7.03872877733453e-30   },
        { 2.8114572543455206e-15, 1.6508842730861433e-31 },
        { 8.22063524662433e-18,   2.2141894119604265e-34 },
        { 1.9572941063391263e-20,-1.3643503830087908e-36 },
        { 3.868170170630684e-23, -8.843177655482344e-40  },
        { 6.446950284384474e-26, -1.9330404233703465e-42 },
    };

    double v = x * x;
    double x3 = x * v;
    double s = ((((((s_fast[7] * v + s_fast[6]) * v + s_fast[5]) * v + s_fast[4]) * v
        + s_fast[3]) * v + s_fast[2]) * v + s_fast[1]) * v + s_fast[0];
    double tail = x3 * s;
    exptab_sum_ hl = exptab_fast2sum_(x, tail);   /* |x| >> |tail| */
    double err = 0x1p-49 * x3;                     /* ~26x the measured slip */
    double lo = hl.hi + (hl.lo - err);
    double hi = hl.hi + (hl.lo + err);
    if (lo == hi)
        return lo;

    /* Accurate leg: c = x^3·S(x^2) as a double-double (degree 11, truncation
     * ~2^-136), then round_anchored adds the exact x and breaks the ties. */
    exptab_sum_ vv = exptab_prod_(x, x);
    exptab_sum_ acc = { s_dd[11][0], s_dd[11][1] };
    for (int i = 10; i >= 0; --i)
        acc = exptab_add_(exptab_mul_(acc, vv), (exptab_sum_){ s_dd[i][0], s_dd[i][1] });
    exptab_sum_ c = exptab_mul_(exptab_mul_((exptab_sum_){ x, 0.0 }, vv), acc);
    return sinhtab_round_anchored_(x, c);
}

/* Hard-to-round database: |x| (>= SINH_SMALL) mapped to its correctly-rounded
 * sinh.  Sorted by x; generated by tools/gen_hyp_wc.c over sinh.wc + random. */
static const struct { double x, y; } sinh_wc_[] = {
    { 0x1.07f309caa4695p-2, 0x1.0ae1c8e723d3p-2 },
    { 0x1.0805c7b507885p-2, 0x1.0af5272381f12p-2 },
    { 0x1.10df5825e6997p-2, 0x1.141d05c0d88e7p-2 },
    { 0x1.38852972acep-2, 0x1.3d64f67d173f1p-2 },
    { 0x1.6660974af4f3ap-2, 0x1.6dbcf9dad0171p-2 },
    { 0x1.846cd6e318895p-2, 0x1.8dcea0b014ec6p-2 },
    { 0x1.ad2cbff58d65bp-2, 0x1.b9d9ad72c6ecdp-2 },
    { 0x1.b5baf341cd4b9p-2, 0x1.c32f0ca64aba7p-2 },
    { 0x1.bc336a6a4596ap-2, 0x1.ca437ee73ecb4p-2 },
    { 0x1.bc5d63fce3f2p-2, 0x1.ca717bd4e783bp-2 },
    { 0x1.c53e658ec4b56p-2, 0x1.d4305496d4619p-2 },
    { 0x1.d3e0d2f5d98d6p-2, 0x1.e45428082fb8cp-2 },
    { 0x1.daa6cb4b223e4p-2, 0x1.ebd505f201686p-2 },
    { 0x1.debf8f265777ap-2, 0x1.f0617f87d709cp-2 },
    { 0x1.fab395f4b6dcp-2, 0x1.07d1269db031dp-1 },
    { 0x1.4bbc536b33214p-1, 0x1.637032fcb3109p-1 },
    { 0x1.4f4082655eb1bp-1, 0x1.67ba309c9d8cfp-1 },
    { 0x1.7b4d19c7b2fedp-1, 0x1.9ef5d79bc5ceep-1 },
    { 0x1.bf7669cf1f8ffp-1, 0x1.faa396e8f86d3p-1 },
    { 0x1.320c3ad433e3fp+0, 0x1.8056f85c06502p+0 },
    { 0x1.39f4ffbc931dcp+0, 0x1.8ecaf44ac417ep+0 },
    { 0x1.7f0046225d651p+1, 0x1.3e11487da075dp+3 },
    { 0x1.f84ad5f18cb85p+1, 0x1.9b1ab16026073p+4 },
    { 0x1.69b7ea44ba7bcp+3, 0x1.3ce147349f63cp+15 },
    { 0x1.4b3ded710bd0fp+5, 0x1.aa1fe6e5bd479p+58 },
    { 0x1.872ea5debf893p+5, 0x1.7566947fb5c2dp+69 },
    { 0x1.519fcf17ae48ep+6, 0x1.b537d1cbcd56fp+120 },
    { 0x1.fe0836c0955b9p+6, 0x1.f0577f00fc36p+182 },
    { 0x1.1c11f1687d68fp+7, 0x1.e21f461cfa82bp+203 },
    { 0x1.622c5afbc0484p+8, 0x1.f362ba5e228d5p+509 },
    { 0x1.8cfadd48a83a2p+8, 0x1.a5f7c6b4300c3p+571 },
    { 0x1.2c1e030b5decdp+9, 0x1.f06050a00839p+864 },
    { 0x1.4f6c9bbf79eb2p+9, 0x1.c706ed8365944p+966 },
};

static double sinh_wc_lookup_(double x)
{
    int lo = 0, hi = (int)(sizeof sinh_wc_ / sizeof *sinh_wc_) - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (sinh_wc_[mid].x < x)
            lo = mid + 1;
        else if (sinh_wc_[mid].x > x)
            hi = mid - 1;
        else
            return sinh_wc_[mid].y;
    }
    return 0;
}

double sinh(double x)
{
    double s = fabs(x);

    /* ln(2·DBL_MAX) ≈ 0x1.633ce8fb9f87dp+9: above this (or NaN) propagate. */
    if (!(s <= 0x1.633ce8fb9f87dp+9))
        return x * HUGE_VAL;

    /* |x| <= 2^-26: sinh(x) rounds to exactly x (the x^3/6 term < 0.5 ulp). */
    if (s < 1.4901161193847656e-8)
        return x;

    /* |x| < ¼: ½(e^x − e^-x) cancels catastrophically, so anchor at the exact x
     * via the odd series instead. */
    if (s < SINH_SMALL)
        return copysign(sinh_small_(s), x);

    /* |x| >= ¼: sinh(x) = ½(e^x − e^-x) = 2^e · mantissa; the residual
     * cancellation is mild (≤ 1 bit), so the double-double carries it. */
    int64_t e;
    exptab_sum_ mantissa = sinhtab_combine_(s, 0, &e);

    double out;
    if (sinhtab_round_(mantissa, e, &out))
        return copysign(out, x);

    double wc = sinh_wc_lookup_(s);
    return copysign(wc ? wc : out, x);
}
