#include "kernel/sinhtab.h"
#include <math.h>
#include <stdint.h>

/* Upper limit of the result-anchored small-|x| series leg. */
#define TANH_SMALL 0.125
/* Lower limit of the large-|x| cheap leg, tanh = 1 − 2/(e^2x + 1). */
#define TANH_LARGE 3.683

/* tanh(x) = x + x^3·T(x^2) for |x| < TANH_SMALL, where E = e^2x − 1 cancels.
 * Unlike sinh's factorially-decaying series, T decays only geometrically, so the
 * fast leg needs degree 8 and the accurate leg degree 15.  Port of metallic-rs
 * tanh_small. */
static double tanh_small_(double x)
{
    static const double t_fast[9] = {
        -0.3333333333333333,    0.13333333333333333,  -0.053968253968253964,
         0.0218694885361552,   -0.008863235529902196,  0.0035921280365724807,
        -0.0014558343870513181, 0.000590027440945586, -0.00023912911424355248,
    };
    static const double t_dd[16][2] = {
        { -0.3333333333333333,   -1.850371707708594e-17  },
        {  0.13333333333333333,   1.8503717077085942e-18 },
        { -0.053968253968253964, -4.383618688500122e-18  },
        {  0.0218694885361552,    3.2956686566529393e-18 },
        { -0.008863235529902196, -9.71422895804976e-19   },
        {  0.0035921280365724807, 3.0829850815353886e-19 },
        { -0.0014558343870513181,-1.5469550809574026e-19 },
        {  0.000590027440945586,  3.478690842383652e-20  },
        { -0.00023912911424355248,-3.564613898329782e-21 },
        {  9.69153795692945e-5,    7.313864280505558e-21 },
        { -3.927832388331683e-5,  -1.3737015743076767e-21},
        {  1.5918905069328964e-5,  1.0427554807190543e-21},
        { -6.451689215655431e-6,  -1.1519922496640055e-22},
        {  2.6147711512907542e-6,  3.3037961741415215e-22},
        { -1.0597268320104654e-6, -2.367052550521363e-24 },
        {  4.294911078273806e-7,   1.1643520863702653e-23},
    };

    double v = x * x;
    double x3 = x * v;
    double s = ((((((((t_fast[8] * v + t_fast[7]) * v + t_fast[6]) * v + t_fast[5]) * v
        + t_fast[4]) * v + t_fast[3]) * v + t_fast[2]) * v + t_fast[1]) * v + t_fast[0]);
    double tail = x3 * s;
    exptab_sum_ hl = exptab_fast2sum_(x, tail);   /* |x| >> |tail| */
    double err = 0x1p-49 * x3;
    double lo = hl.hi + (hl.lo - err);
    double hi = hl.hi + (hl.lo + err);
    if (lo == hi)
        return lo;

    exptab_sum_ vv = exptab_prod_(x, x);
    exptab_sum_ acc = { t_dd[15][0], t_dd[15][1] };
    for (int i = 14; i >= 0; --i)
        acc = exptab_add_(exptab_mul_(acc, vv), (exptab_sum_){ t_dd[i][0], t_dd[i][1] });
    exptab_sum_ c = exptab_mul_(exptab_mul_((exptab_sum_){ x, 0.0 }, vv), acc);
    return sinhtab_round_anchored_(x, c);
}

/* Hard-to-round database: |x| (TANH_SMALL <= |x| < 20) mapped to its
 * correctly-rounded tanh.  Sorted by x; generated by tools/gen_hyp_wc.c. */
static const struct { double x, y; } tanh_wc_[] = {
    { 0x1.004524207fad9p-3, 0x1.fde1b6fff6ef9p-4 },
    { 0x1.179173ab2cd77p-3, 0x1.15d8306fc4a28p-3 },
    { 0x1.511b50db9ebaap-3, 0x1.4e184523b3263p-3 },
    { 0x1.a9a549a0bd08dp-3, 0x1.a39f0020a6a6dp-3 },
    { 0x1.ac343b179fec4p-3, 0x1.a612499c53078p-3 },
    { 0x1.c5ade7c872488p-3, 0x1.be66adf0ebdf4p-3 },
    { 0x1.1005ec0bccabbp-1, 0x1.f20b1c8557decp-2 },
    { 0x1.5319f57633346p+0, 0x1.bc60ed585d873p-1 },
};

static double tanh_wc_lookup_(double x)
{
    int lo = 0, hi = (int)(sizeof tanh_wc_ / sizeof *tanh_wc_) - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (tanh_wc_[mid].x < x)
            lo = mid + 1;
        else if (tanh_wc_[mid].x > x)
            hi = mid - 1;
        else
            return tanh_wc_[mid].y;
    }
    return 0;
}

double tanh(double x)
{
    double s = fabs(x);

    if (isnan(x))
        return x;

    /* |x| >= 20: tanh rounds to exactly ±1 (and e^2x would overflow below). */
    if (s >= 20.0)
        return copysign(1.0, x);

    /* |x| <= 2^-27: tanh(x) rounds to exactly x (the x^3/3 term < 0.5 ulp). */
    if (s < 7.450580596923828e-9)
        return x;

    /* |x| < ⅛: E = e^2x − 1 cancels, so anchor at the exact x via the series. */
    if (s < TANH_SMALL)
        return copysign(tanh_small_(s), x);

    /* |x| ∈ [⅛, 20): e^2x = 2^q·m, computed once for both legs below. */
    int64_t q;
    exptab_sum_ m = sinhtab_exp_dd_(2.0 * s, &q);

    /* |x| >= 3.683: tanh = 1 − 2/(e^2x + 1), the correction ≤ ~1.3e-3 small
     * enough that the plain-f64 e^2x high word and one division round it
     * correctly (Ziv-gated).  CORE-MATH's cheap large-|x| leg. */
    if (s >= TANH_LARGE) {
        double corr = 2.0 / (shift_(m.hi, q) + 1.0);
        double err = corr * 0x1.1p-49;
        double lo = 1.0 - (corr + err);
        double hi = 1.0 - (corr - err);
        if (lo == hi)
            return copysign(lo, x);
    }

    /* |x| ∈ [⅛, 20): tanh = 1 − 2/(e^2x + 1); never cancels here. */
    int64_t e;
    exptab_sum_ mantissa = sinhtab_tanh_combine_(m, q, &e);

    double out;
    if (sinhtab_round_(mantissa, e, &out))
        return copysign(out, x);

    double wc = tanh_wc_lookup_(s);
    return copysign(wc ? wc : out, x);
}
