/* Generated by metallic-rs tools/gen_pow_f128.py; do not edit by hand. */
#ifndef METALLIC_MATH_LONG_DOUBLE_KERNEL_POWTAB_H
#define METALLIC_MATH_LONG_DOUBLE_KERNEL_POWTAB_H

#include <stdint.h>

/* ln(2), scaled by 2^640 and truncated. */
static const uint64_t POW_LN2[10] = {
    0x1acbda11317c387e, 0x3e96ca16224ae8c5,
    0x27573b291169b825, 0xed2eae35c1382144,
    0x559552fb4afa1b10, 0xe7b876206debac98,
    0x8a0d175b8baafa2b, 0x40f343267298b62d,
    0xc9e3b39803f2f6af, 0xb17217f7d1cf79ab,
};

/* log2(e), scaled by 2^639 and truncated. */
static const uint64_t POW_LOG2E[10] = {
    0xb21b43d579d5a206, 0x2fe294932617d9d5,
    0xc4bfaf0353df39b3, 0xea90b9e60c4a909f,
    0x24d92f75c16be0b3, 0xde1c43f755176cd6,
    0x8b25166cd1a13247, 0xeb577aa8dd695a58,
    0xbe87fed0691d3e88, 0xb8aa3b295c17f0bb,
};

#endif
