#ifndef METALLIC_FLOAT_KERNEL_ASINPIF_H
#define METALLIC_FLOAT_KERNEL_ASINPIF_H

#include <stdint.h>

/* Shared 16-cell table of asinpif and acospif (metallic-rs f32_/atan.rs;
 * CORE-MATH's one-step shape, metallic-rs's own fits): cell 0 holds q in
 * asinpi(z) ~ z*q(z^2) for |x| < 1/16; cell i >= 1 holds a degree-7 fit of
 * g(a) = (1/2 - asinpi(a))/sqrt(1-a) = acospi(a)/sqrt(1-a) on
 * a in [i/16, (i+1)/16), whence asinpi(x) = sign(x)*(1/2 - g*sqrt(1-|x|))
 * and acospi(x) = g*sqrt(1-|x|) for x >= 0 (folded about 1 below).  The
 * polynomial evaluates in parallel with the square root, and 1 - |x| is
 * exact there, so a single combine lands the result with no rounding test
 * or fallback tier.
 *
 * Worst per-cell sup relative error 2^-53.8 (cell 0; the reflection cells
 * sit at 2^-55..2^-61), leaving ~10^5 margin on the binding constraint.
 * Generated by metallic-rs tools/gen_asinpi_f32.py (rminimax ratapprox,
 * relative weight).  Rows are 64 bytes: one cache line per cell. */
static const double asinpi_cells_[16][8] = {
    /* asin(sqrt(x))/(pi*sqrt(x)) on [1e-30,0.00390625] */
    { 0x1.45f306dc9c883p-2, 0x1.b2995e7b74c34p-5, 0x1.8723a2644964ep-6, 0x1.d19f0446f5860p-7,
      0x1.49dc2b4ff36c0p-7, -0x1.00ca4c46ecffdp-3, 0x1.69ade0296417ep+4, -0x1.816fb0d8561dep+10 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.0625,0.125] */
    { 0x1.ffffffffd3c67p-2, -0x1.17cc1b334d242p-4, 0x1.d067a1e4308fbp-6, -0x1.08e16f5abfee9p-6,
      0x1.5eed3c781e3e6p-7, -0x1.f58b4ca9cea80p-8, 0x1.5daa0c6a1b0d2p-8, -0x1.5922f470a0401p-9 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.125,0.1875] */
    { 0x1.fffffff7c3a9ap-2, -0x1.17cc149d69300p-4, 0x1.d0654d2468f9bp-6, -0x1.08c3b8bda912dp-6,
      0x1.5d203d483a581p-7, -0x1.e48541af597e7p-8, 0x1.303a4095562b8p-8, -0x1.dee39e1cb4531p-10 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.1875,0.25] */
    { 0x1.ffffffa7446acp-2, -0x1.17cbe712c5952p-4, 0x1.d05a3093d9aeep-6, -0x1.0862afa8bfe18p-6,
      0x1.5920494ba000cp-7, -0x1.cb038b9cc2bb3p-8, 0x1.02b6daa483098p-8, -0x1.52a45ac53f1b8p-10 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.25,0.3125] */
    { 0x1.fffffe1f7edbcp-2, -0x1.17cb3e6cff85ap-4, 0x1.d03af5258ec86p-6, -0x1.07943a0b783fep-6,
      0x1.52b3f12c66034p-7, -0x1.ac319a6d2f952p-8, 0x1.b2eef01bd5b18p-9, -0x1.e73c6a15c2754p-11 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.3125,0.375] */
    { 0x1.fffff92bb4699p-2, -0x1.17c986ed010bep-4, 0x1.cff97f000655fp-6, -0x1.0638a9e029d8fp-6,
      0x1.4a07bf545ecf6p-7, -0x1.8adddbcc25860p-8, 0x1.6b98ad14c8e28p-9, -0x1.640220be09a50p-11 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.375,0.4375] */
    { 0x1.ffffecce6c1ecp-2, -0x1.17c5f15467808p-4, 0x1.cf874a835a66fp-6, -0x1.043e5d59c041ep-6,
      0x1.3f7d6724037ecp-7, -0x1.69198bfceaac4p-8, 0x1.2f63cd5498321p-9, -0x1.07d3cc4d9982bp-11 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.4375,0.5] */
    { 0x1.ffffd2f567278p-2, -0x1.17bf81d5135ecp-4, 0x1.ced7434fc2140p-6, -0x1.01a0c09beb9d4p-6,
      0x1.3388aaeac7334p-7, -0x1.484418bb1e318p-8, 0x1.fa7533f9731f8p-10, -0x1.8c1c1457f8f80p-12 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.5,0.5625] */
    { 0x1.ffffa36b874f5p-2, -0x1.17b52344aa9bap-4, 0x1.cddedb2514090p-6, -0x1.fccad2ea117cap-7,
      0x1.269aa6032d3e0p-7, -0x1.293252573e91fp-8, 0x1.a76b604aac6c8p-10, -0x1.2ce5c8db4188cp-12 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.5625,0.625] */
    { 0x1.ffff54003f4ecp-2, -0x1.17a5ba1380280p-4, 0x1.cc9680443f8bbp-6, -0x1.f531e17341be7p-7,
      0x1.1917b5cdf3b9ep-7, -0x1.0c56946909ed0p-8, 0x1.62e0e802df06ap-10, -0x1.ce25e7076a8ebp-13 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.625,0.6875] */
    { 0x1.fffed8d307926p-2, -0x1.17903416bd364p-4, 0x1.caf99b3a7fb8fp-6, -0x1.ec983971fef14p-7,
      0x1.0b537801e8e68p-7, -0x1.e3c1134bc1938p-9, 0x1.2a541d3c84698p-10, -0x1.667dfa6cde428p-13 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.6875,0.75] */
    { 0x1.fffe24b2260f6p-2, -0x1.1773943b91628p-4, 0x1.c906464d49923p-6, -0x1.e323575f0b894p-7,
      0x1.fb20e63d59418p-8, -0x1.b3a9ce94e913bp-9, 0x1.f73e2abb22caep-11, -0x1.18af3bde3f5f9p-13 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.75,0.8125] */
    { 0x1.fffd2984f46c8p-2, -0x1.174efb033008ap-4, 0x1.c6bcef45a2493p-6, -0x1.d8f9b288ab81ep-7,
      0x1.e003ab2aade57p-8, -0x1.883d2703f2978p-9, 0x1.a9ef351d5cdf2p-11, -0x1.bb58560397a1cp-14 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.8125,0.875] */
    { 0x1.fffbd8af0d13ap-2, -0x1.1721aac4076a8p-4, 0x1.c41fded418944p-6, -0x1.ce407f08c0100p-7,
      0x1.c59ad5d042cb2p-8, -0x1.6132ffc7f3e3dp-9, 0x1.69c986c06622cp-11, -0x1.60f72647c0091p-14 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.875,0.9375] */
    { 0x1.fffa236a097aep-2, -0x1.16eb093b92e36p-4, 0x1.c132c677a444bp-6, -0x1.c31a5752ddbe0p-7,
      0x1.ac1bd1dadac48p-8, -0x1.3e343bad5df0cp-9, 0x1.34662cac4082ap-11, -0x1.1b212891bc800p-14 },
    /* (0.5 - asin(x)/pi)/sqrt(1-x) on [0.9375,0.999999999999] */
    { 0x1.fff7fb12c8804p-2, -0x1.16aa9f29212f2p-4, 0x1.bdfa5b6cc9200p-6, -0x1.b7a686e3042dfp-7,
      0x1.93aa497ff89f8p-8, -0x1.1ee46ba1fd0dcp-9, 0x1.07d1cd803e3d8p-11, -0x1.c96c39494ef9ep-15 },
};

/* Cell index: floor(16|x|) for |x| >= 2^-12 and 0 below, straight from the
 * bits (the & 15 is provably a no-op and elides any bounds concern). */
static int asinpi_cell_index_(uint32_t bits)
{
    uint32_t shift = 146 - ((bits >> 23) & 0xFF);
    return shift < 32 ? (int)((((bits & 0x007FFFFF) | 0x00800000) >> shift) & 15) : 0;
}

/* Degree-7 Estrin evaluation, the shape the cells were fitted with. */
static double asinpi_poly_(double x, const double c[8])
{
    double x2 = x * x;
    double x4 = x2 * x2;
    double lo = x2 * (x * c[3] + c[2]) + (x * c[1] + c[0]);
    double hi = x2 * (x * c[7] + c[6]) + (x * c[5] + c[4]);

    return x4 * hi + lo;
}

#endif
